[package]
name = "vpn-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[dependencies]
# Workspace deps
tokio.workspace = true
quinn.workspace = true
trust-dns-resolver.workspace = true
ring.workspace = true
x25519-dalek = { workspace = true, features = ["static_secrets"] }
chacha20poly1305.workspace = true
ed25519-dalek = { workspace = true, features = ["pkcs8", "rand_core"] }
curve25519-dalek = "4.1"
libloading = "0.8"
hkdf.workspace = true
sha2.workspace = true
zeroize.workspace = true
secrecy.workspace = true
bincode.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
anyhow.workspace = true
tracing.workspace = true
async-trait.workspace = true
futures.workspace = true

# NAT Traversal
stun = "0.5"
webrtc-ice = "0.9"

# Shared deps
base64 = "0.21"
uuid = { version = "1.0", features = ["v4"] }
rand = "0.8"
serde_yaml = "0.9.34"
chrono = { version = "0.4.43", features = ["serde"] }
flutter_rust_bridge = "=2.12.0"
lazy_static = "1.4"
parking_lot = "0.12"
tracing-subscriber.workspace = true
dotenvy = "0.15.7"
hex = "0.4.3"
reqwest = { version = "0.13.3", features = ["json", "gzip", "rustls", "multipart", "blocking", "form"] }
libp2p = { version = "0.53", features = ["tokio", "kad", "gossipsub", "mdns", "tcp", "noise", "yamux", "macros", "dns"] }
lru = "0.12"
ss-uri = "0.3.0"
regex = "1.12.3"

