// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_backend_url`, `send_status`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AUTH_TOKEN`, `BACKEND_URL`, `ConnectionStatus`, `IS_SHARING`, `LOGGED_USER`, `MobileVpnState`, `SHARING_TASK`, `STATUS_STREAM`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `deref`, `deref`, `deref`, `deref`, `deref`, `deref`, `eq`, `fmt`, `fmt`, `fmt`, `initialize`, `initialize`, `initialize`, `initialize`, `initialize`, `initialize`

Future<void> setBackendUrl({required String url}) =>
    RustLib.instance.api.crateApiSimpleSetBackendUrl(url: url);

Future<String> greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

Future<Uint8List> generateIdentity() =>
    RustLib.instance.api.crateApiSimpleGenerateIdentity();

Future<String> loginAnonymously({required List<int> privateKeyBytes}) =>
    RustLib.instance.api
        .crateApiSimpleLoginAnonymously(privateKeyBytes: privateKeyBytes);

Future<String> startVpnMatchmaking(
        {required String protocolStr,
        required String countryCode,
        required String nodeGroup}) =>
    RustLib.instance.api.crateApiSimpleStartVpnMatchmaking(
        protocolStr: protocolStr,
        countryCode: countryCode,
        nodeGroup: nodeGroup);

Future<void> startSharing() =>
    RustLib.instance.api.crateApiSimpleStartSharing();

Future<void> stopSharing() => RustLib.instance.api.crateApiSimpleStopSharing();

Future<bool> isSharing() => RustLib.instance.api.crateApiSimpleIsSharing();

Future<void> stopVpnConnection() =>
    RustLib.instance.api.crateApiSimpleStopVpnConnection();

Stream<VpnStatusEvent> registerStatusStream() =>
    RustLib.instance.api.crateApiSimpleRegisterStatusStream();

Future<PlatformInt64> getWalletBalance() =>
    RustLib.instance.api.crateApiSimpleGetWalletBalance();

class VpnStatusEvent {
  final String status;
  final String protocol;
  final double downloadSpeed;
  final double uploadSpeed;

  const VpnStatusEvent({
    required this.status,
    required this.protocol,
    required this.downloadSpeed,
    required this.uploadSpeed,
  });

  @override
  int get hashCode =>
      status.hashCode ^
      protocol.hashCode ^
      downloadSpeed.hashCode ^
      uploadSpeed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VpnStatusEvent &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          protocol == other.protocol &&
          downloadSpeed == other.downloadSpeed &&
          uploadSpeed == other.uploadSpeed;
}
