// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `STATUS_STREAM`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `deref`, `fmt`, `initialize`

Future<String> greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

Future<void> startVpnConnection(
        {required String protocol, required String countryCode}) =>
    RustLib.instance.api.crateApiSimpleStartVpnConnection(
        protocol: protocol, countryCode: countryCode);

Future<void> stopVpnConnection() =>
    RustLib.instance.api.crateApiSimpleStopVpnConnection();

Stream<VpnStatusEvent> registerStatusStream() =>
    RustLib.instance.api.crateApiSimpleRegisterStatusStream();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ConnectionStatus>>
abstract class ConnectionStatus implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MobileVpnState>>
abstract class MobileVpnState implements RustOpaqueInterface {
  BigInt get bytesDown;

  BigInt get bytesUp;

  String? get currentIp;

  ConnectionStatus get status;

  set bytesDown(BigInt bytesDown);

  set bytesUp(BigInt bytesUp);

  set currentIp(String? currentIp);

  set status(ConnectionStatus status);
}

class VpnStatusEvent {
  final String status;
  final String protocol;
  final double downloadSpeed;
  final double uploadSpeed;

  const VpnStatusEvent({
    required this.status,
    required this.protocol,
    required this.downloadSpeed,
    required this.uploadSpeed,
  });

  @override
  int get hashCode =>
      status.hashCode ^
      protocol.hashCode ^
      downloadSpeed.hashCode ^
      uploadSpeed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VpnStatusEvent &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          protocol == other.protocol &&
          downloadSpeed == other.downloadSpeed &&
          uploadSpeed == other.uploadSpeed;
}
