// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 1896651409;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'vpn_core',
    ioDirectory: '../../crates/vpn-core/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  BigInt crateApiSimpleMobileVpnStateAutoAccessorGetBytesDown(
      {required MobileVpnState that});

  BigInt crateApiSimpleMobileVpnStateAutoAccessorGetBytesUp(
      {required MobileVpnState that});

  String? crateApiSimpleMobileVpnStateAutoAccessorGetCurrentIp(
      {required MobileVpnState that});

  ConnectionStatus crateApiSimpleMobileVpnStateAutoAccessorGetStatus(
      {required MobileVpnState that});

  void crateApiSimpleMobileVpnStateAutoAccessorSetBytesDown(
      {required MobileVpnState that, required BigInt bytesDown});

  void crateApiSimpleMobileVpnStateAutoAccessorSetBytesUp(
      {required MobileVpnState that, required BigInt bytesUp});

  void crateApiSimpleMobileVpnStateAutoAccessorSetCurrentIp(
      {required MobileVpnState that, String? currentIp});

  void crateApiSimpleMobileVpnStateAutoAccessorSetStatus(
      {required MobileVpnState that, required ConnectionStatus status});

  Future<String> crateApiSimpleGreet({required String name});

  Stream<VpnStatusEvent> crateApiSimpleRegisterStatusStream();

  Future<void> crateApiSimpleStartVpnConnection(
      {required String protocol, required String countryCode});

  Future<void> crateApiSimpleStopVpnConnection();

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_ConnectionStatus;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_ConnectionStatus;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_ConnectionStatusPtr;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_MobileVpnState;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_MobileVpnState;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_MobileVpnStatePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  BigInt crateApiSimpleMobileVpnStateAutoAccessorGetBytesDown(
      {required MobileVpnState that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileVpnState(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_u_64,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleMobileVpnStateAutoAccessorGetBytesDownConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiSimpleMobileVpnStateAutoAccessorGetBytesDownConstMeta =>
          const TaskConstMeta(
            debugName: "MobileVpnState_auto_accessor_get_bytes_down",
            argNames: ["that"],
          );

  @override
  BigInt crateApiSimpleMobileVpnStateAutoAccessorGetBytesUp(
      {required MobileVpnState that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileVpnState(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_u_64,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleMobileVpnStateAutoAccessorGetBytesUpConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiSimpleMobileVpnStateAutoAccessorGetBytesUpConstMeta =>
          const TaskConstMeta(
            debugName: "MobileVpnState_auto_accessor_get_bytes_up",
            argNames: ["that"],
          );

  @override
  String? crateApiSimpleMobileVpnStateAutoAccessorGetCurrentIp(
      {required MobileVpnState that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileVpnState(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleMobileVpnStateAutoAccessorGetCurrentIpConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiSimpleMobileVpnStateAutoAccessorGetCurrentIpConstMeta =>
          const TaskConstMeta(
            debugName: "MobileVpnState_auto_accessor_get_current_ip",
            argNames: ["that"],
          );

  @override
  ConnectionStatus crateApiSimpleMobileVpnStateAutoAccessorGetStatus(
      {required MobileVpnState that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileVpnState(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConnectionStatus,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleMobileVpnStateAutoAccessorGetStatusConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiSimpleMobileVpnStateAutoAccessorGetStatusConstMeta =>
          const TaskConstMeta(
            debugName: "MobileVpnState_auto_accessor_get_status",
            argNames: ["that"],
          );

  @override
  void crateApiSimpleMobileVpnStateAutoAccessorSetBytesDown(
      {required MobileVpnState that, required BigInt bytesDown}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileVpnState(
            that, serializer);
        sse_encode_u_64(bytesDown, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleMobileVpnStateAutoAccessorSetBytesDownConstMeta,
      argValues: [that, bytesDown],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiSimpleMobileVpnStateAutoAccessorSetBytesDownConstMeta =>
          const TaskConstMeta(
            debugName: "MobileVpnState_auto_accessor_set_bytes_down",
            argNames: ["that", "bytesDown"],
          );

  @override
  void crateApiSimpleMobileVpnStateAutoAccessorSetBytesUp(
      {required MobileVpnState that, required BigInt bytesUp}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileVpnState(
            that, serializer);
        sse_encode_u_64(bytesUp, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleMobileVpnStateAutoAccessorSetBytesUpConstMeta,
      argValues: [that, bytesUp],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiSimpleMobileVpnStateAutoAccessorSetBytesUpConstMeta =>
          const TaskConstMeta(
            debugName: "MobileVpnState_auto_accessor_set_bytes_up",
            argNames: ["that", "bytesUp"],
          );

  @override
  void crateApiSimpleMobileVpnStateAutoAccessorSetCurrentIp(
      {required MobileVpnState that, String? currentIp}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileVpnState(
            that, serializer);
        sse_encode_opt_String(currentIp, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleMobileVpnStateAutoAccessorSetCurrentIpConstMeta,
      argValues: [that, currentIp],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiSimpleMobileVpnStateAutoAccessorSetCurrentIpConstMeta =>
          const TaskConstMeta(
            debugName: "MobileVpnState_auto_accessor_set_current_ip",
            argNames: ["that", "currentIp"],
          );

  @override
  void crateApiSimpleMobileVpnStateAutoAccessorSetStatus(
      {required MobileVpnState that, required ConnectionStatus status}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileVpnState(
            that, serializer);
        sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConnectionStatus(
            status, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleMobileVpnStateAutoAccessorSetStatusConstMeta,
      argValues: [that, status],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiSimpleMobileVpnStateAutoAccessorSetStatusConstMeta =>
          const TaskConstMeta(
            debugName: "MobileVpnState_auto_accessor_set_status",
            argNames: ["that", "status"],
          );

  @override
  Future<String> crateApiSimpleGreet({required String name}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(name, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleGreetConstMeta,
      argValues: [name],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta => const TaskConstMeta(
        debugName: "greet",
        argNames: ["name"],
      );

  @override
  Stream<VpnStatusEvent> crateApiSimpleRegisterStatusStream() {
    final sink = RustStreamSink<VpnStatusEvent>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_StreamSink_vpn_status_event_Sse(sink, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSimpleRegisterStatusStreamConstMeta,
      argValues: [sink],
      apiImpl: this,
    )));
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSimpleRegisterStatusStreamConstMeta =>
      const TaskConstMeta(
        debugName: "register_status_stream",
        argNames: ["sink"],
      );

  @override
  Future<void> crateApiSimpleStartVpnConnection(
      {required String protocol, required String countryCode}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(protocol, serializer);
        sse_encode_String(countryCode, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSimpleStartVpnConnectionConstMeta,
      argValues: [protocol, countryCode],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleStartVpnConnectionConstMeta =>
      const TaskConstMeta(
        debugName: "start_vpn_connection",
        argNames: ["protocol", "countryCode"],
      );

  @override
  Future<void> crateApiSimpleStopVpnConnection() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSimpleStopVpnConnectionConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleStopVpnConnectionConstMeta =>
      const TaskConstMeta(
        debugName: "stop_vpn_connection",
        argNames: [],
      );

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_ConnectionStatus => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConnectionStatus;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_ConnectionStatus => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConnectionStatus;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_MobileVpnState => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileVpnState;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_MobileVpnState => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileVpnState;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  ConnectionStatus
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConnectionStatus(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ConnectionStatusImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  MobileVpnState
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileVpnState(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MobileVpnStateImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  MobileVpnState
      dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileVpnState(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MobileVpnStateImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  MobileVpnState
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileVpnState(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MobileVpnStateImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ConnectionStatus
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConnectionStatus(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ConnectionStatusImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  MobileVpnState
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileVpnState(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MobileVpnStateImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<VpnStatusEvent> dco_decode_StreamSink_vpn_status_event_Sse(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  VpnStatusEvent dco_decode_vpn_status_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return VpnStatusEvent(
      status: dco_decode_String(arr[0]),
      protocol: dco_decode_String(arr[1]),
      downloadSpeed: dco_decode_f_64(arr[2]),
      uploadSpeed: dco_decode_f_64(arr[3]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  ConnectionStatus
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConnectionStatus(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ConnectionStatusImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  MobileVpnState
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileVpnState(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return MobileVpnStateImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  MobileVpnState
      sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileVpnState(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return MobileVpnStateImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  MobileVpnState
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileVpnState(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return MobileVpnStateImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  ConnectionStatus
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConnectionStatus(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ConnectionStatusImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  MobileVpnState
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileVpnState(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return MobileVpnStateImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  RustStreamSink<VpnStatusEvent> sse_decode_StreamSink_vpn_status_event_Sse(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  VpnStatusEvent sse_decode_vpn_status_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_status = sse_decode_String(deserializer);
    var var_protocol = sse_decode_String(deserializer);
    var var_downloadSpeed = sse_decode_f_64(deserializer);
    var var_uploadSpeed = sse_decode_f_64(deserializer);
    return VpnStatusEvent(
        status: var_status,
        protocol: var_protocol,
        downloadSpeed: var_downloadSpeed,
        uploadSpeed: var_uploadSpeed);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConnectionStatus(
          ConnectionStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as ConnectionStatusImpl).frbInternalSseEncode(move: true),
        serializer);
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileVpnState(
          MobileVpnState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as MobileVpnStateImpl).frbInternalSseEncode(move: true),
        serializer);
  }

  @protected
  void
      sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileVpnState(
          MobileVpnState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as MobileVpnStateImpl).frbInternalSseEncode(move: false),
        serializer);
  }

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileVpnState(
          MobileVpnState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as MobileVpnStateImpl).frbInternalSseEncode(move: false),
        serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerConnectionStatus(
          ConnectionStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as ConnectionStatusImpl).frbInternalSseEncode(move: null),
        serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileVpnState(
          MobileVpnState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as MobileVpnStateImpl).frbInternalSseEncode(move: null),
        serializer);
  }

  @protected
  void sse_encode_StreamSink_vpn_status_event_Sse(
      RustStreamSink<VpnStatusEvent> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
        self.setupAndSerialize(
            codec: SseCodec(
          decodeSuccessData: sse_decode_vpn_status_event,
          decodeErrorData: sse_decode_AnyhowException,
        )),
        serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_vpn_status_event(
      VpnStatusEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.status, serializer);
    sse_encode_String(self.protocol, serializer);
    sse_encode_f_64(self.downloadSpeed, serializer);
    sse_encode_f_64(self.uploadSpeed, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}

@sealed
class ConnectionStatusImpl extends RustOpaque implements ConnectionStatus {
  // Not to be used by end users
  ConnectionStatusImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ConnectionStatusImpl.frbInternalSseDecode(
      BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_ConnectionStatus,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_ConnectionStatus,
    rustArcDecrementStrongCountPtr: RustLib
        .instance.api.rust_arc_decrement_strong_count_ConnectionStatusPtr,
  );
}

@sealed
class MobileVpnStateImpl extends RustOpaque implements MobileVpnState {
  // Not to be used by end users
  MobileVpnStateImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  MobileVpnStateImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_MobileVpnState,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_MobileVpnState,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_MobileVpnStatePtr,
  );

  BigInt get bytesDown =>
      RustLib.instance.api.crateApiSimpleMobileVpnStateAutoAccessorGetBytesDown(
        that: this,
      );

  BigInt get bytesUp =>
      RustLib.instance.api.crateApiSimpleMobileVpnStateAutoAccessorGetBytesUp(
        that: this,
      );

  String? get currentIp =>
      RustLib.instance.api.crateApiSimpleMobileVpnStateAutoAccessorGetCurrentIp(
        that: this,
      );

  ConnectionStatus get status =>
      RustLib.instance.api.crateApiSimpleMobileVpnStateAutoAccessorGetStatus(
        that: this,
      );

  set bytesDown(BigInt bytesDown) =>
      RustLib.instance.api.crateApiSimpleMobileVpnStateAutoAccessorSetBytesDown(
          that: this, bytesDown: bytesDown);

  set bytesUp(BigInt bytesUp) =>
      RustLib.instance.api.crateApiSimpleMobileVpnStateAutoAccessorSetBytesUp(
          that: this, bytesUp: bytesUp);

  set currentIp(String? currentIp) =>
      RustLib.instance.api.crateApiSimpleMobileVpnStateAutoAccessorSetCurrentIp(
          that: this, currentIp: currentIp);

  set status(ConnectionStatus status) =>
      RustLib.instance.api.crateApiSimpleMobileVpnStateAutoAccessorSetStatus(
          that: this, status: status);
}
